routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::view('/login', 'login/index');

// Route::group(['middleware' => 'guest'], function () {

// });
Route::get('/login', 'Auth\LoginController@login')->name('login')->middleware('guest');;
Route::post('/login', 'Auth\LoginController@doLogin');
// Route::get('logout', array('uses' => 'Auth\LoginController@doLogout'));
Route::get('/logout', 'Auth\LoginController@doLogout')->name('logout');


    Route::view('/', 'dashboard/index')->name('dashboard');
    Route::view('/dashboard', 'dashboard/index')->name('dashboard');

    Route::view('/password-recovery', 'password_recovery/index')->name('password_recovery');

    Route::get('contract', function () {
        return view('contract/contract_customer');
    })->name('contract');

    Route::get('representative', function () {
        return view('contract/contract_representative');
    })->name('representative');

    Route::get('/manage-contract', function () {
        return view('contract/manage_contract');
    })->name('manage-contract');

    Route::get('contract-infor', function () {
        return view('contract/contract_infor');
    })->name('contract-infor');

    Route::get('contract-connection', function () {
        return view('contract/contract_connection');
    })->name('contract-connection');

    Route::get('contract-search', function () {
        return view('contract/contract_search');
    })->name('search');

    Route::resource('/baseplacement', 'Master\BaseplacemstController');

    Route::resource('/user', 'Master\UserController');
    
    Route::resource('/notice', 'NoticeController');

    Route::view('support-notice', 'support_notice/index')->name('support-notice');

    Route::view('billing', 'billing/index')->name('billing');


Route::resource('/phone', 'PhoneController');

app/Http/Controllers/NoticeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\Announcement\AnnouncementRepositoryInterface;

class NoticeController extends Controller
{
    public function __construct(
        AnnouncementRepositoryInterface $announcement
    )
    {
        $this->announcementRepository = $announcement;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $listNotice = $this->announcementRepository->getAll();
        $listNotice = $this->announcementRepository->getAll();
        return view('notice.list', compact('listNotice'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('notice.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = [
            'title' => 'required',
            'registrationDate' => 'required',
            'expirationDateTime' => 'required',
            'body' => 'required',
        ];
        $request->validate($validate);

        $attributes = [
            'title' => $request->title,
            'registrationDate' => $request->registrationDate,
            'expirationDateTime' => $request->expirationDateTime,
            'tenantID' => $request->tenantID,
            'body' => $request->body,
            'updateDate' => date("Y-m-d H:i:s"),
            'version' => 0,
        ];

        $this->announcementRepository->create($attributes);
        return redirect()->route('notice.index')->with('msg', CREATE_SUCCESS);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $notice = $this->announcementRepository->find($id);
        return view('notice.edit_delete', compact('notice'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = [
            'title' => 'required',
            'registrationDate' => 'required',
            'expirationDateTime' => 'required',
            'body' => 'required',
        ];
        $request->validate($validate);

        $attributes = [
            'title' => $request->title,
            'registrationDate' => $request->registrationDate,
            'expirationDateTime' => $request->expirationDateTime,
            'tenantID' => $request->tenantID,
            'body' => $request->body,
            'updateDate' => date("Y-m-d H:i:s"),
            'version' => 0,
        ];
        $this->announcementRepository->update($id, $attributes);
        return redirect()->route('notice.index')->with('msg', UPDATE_SUCCESS);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->announcementRepository->delete($id);
        return redirect()->route('notice.index')->with('msg', DELETE_SUCCESS);
    }
}

resources/views/notice/add.blade.php
@section('styles')
<link rel="stylesheet" href="{{ asset('css/jquery.datetimepicker.css') }}" type="text/css">
@endsection
@extends('layouts.master')
@section('content')
<h3 class="mt-4">｜　お知らせ登録</h3>
<br>
<div class="card">
    <form action="{{route('notice.store')}}" method="POST">
        @csrf
        <div class="card-body">
            <div class="form-group row">
                <div class="col-sm-2">
                    <div class="row">
                        <label for="staticEmail" class="col-sm-6 col-form-label">タイトル</label>
                        <div class="col-sm-6 text-center"><span class="badge badge-danger align-middle">必須</span></div>
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-11">
                            <input type="text" name="title" class="form-control">
                            @error('title')
                                <h6 class="text-danger">(*){{ $message }}</h6>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-2">
                    <div class="row">
                        <label for="staticEmail" class="col-sm-6 col-form-label">公開開始日時</label>
                        <div class="col-sm-6 text-center"><span class="badge badge-danger align-middle">必須</span></div>
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-11">
                            <input type="text" name="registrationDate" class="form-control registrationDate">
                            @error('registrationDate')
                                <h6 class="text-danger">(*){{ $message }}</h6>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-2">
                    <div class="row">
                        <label for="staticEmail" class="col-sm-6 col-form-label">公開終了日時</label>
                        <div class="col-sm-6 text-center"><span class="badge badge-danger align-middle">必須</span></div>
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-11">
                            <input type="text" name="expirationDateTime" class="form-control expirationDateTime">
                            @error('expirationDateTime')
                                <h6 class="text-danger">(*){{ $message }}</h6>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">通知対象契約顧客</label>
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-11">
                            <div class="row">
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="tenantID" readonly>
                                </div>
                                <div class="col-sm-2">
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-md btn-primary w-100" data-toggle="modal" data-target="#modalNoticeAdd">
                                        戻る
                                    </button>

                                    <!-- Modal -->
                                    <div class="modal fade mt-5" id="modalNoticeAdd" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <table class="table table-bordered text-center" id="tableAddTenant">
                                                        <thead class="thead-dark">
                                                            <tr>
                                                                <th scope="col">TENANTID</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr class="clickableRow">
                                                                <td>1</th>
                                                            </tr>
                                                            <tr class="clickableRow">
                                                                <td>2</th>
                                                            </tr>
                                                            <tr class="clickableRow">
                                                                <td>3</th>
                                                            </tr>
                                                            <tr class="clickableRow">
                                                                <td>4</th>
                                                            </tr>
                                                    </table>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="button" class="btn btn-primary" id="saveAddTenant">Save changes</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- <div class="col-sm-1">
                            <button type="button" class="btn btn-success rounded-circle" aria-label="Close"><i class="fa fa-times"></i></button>
                        </div> -->
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-2">
                    <div class="row">
                        <label for="staticEmail" class="col-sm-6 col-form-label">本文</label>
                        <div class="col-sm-6 text-center"><span class="badge badge-danger align-middle">必須</span></div>
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-11">
                            <textarea class="form-control" rows="4" name="body"></textarea>
                            @error('body')
                                <h6 class="text-danger">(*){{ $message }}</h6>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3"></div>
                <div class="col-sm-9">
                    <div class="row text-center">
                        <div class="col-sm-3">
                            <a href="{{route('notice.index')}}"><input type="button" class="btn btn-md btn-success w-50" value="戻る"></a>
                        </div>
                        <div class="col-sm-3"></div>
                        <div class="col-sm-3">
                            <button class="btn btn-md btn-success w-50" id="notice-add-button">登録</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection
@section('scripts')
<script type="text/javascript" src="{{asset('js/notice/add.js')}}"></script>
<script type="text/javascript" src="{{asset('js/jquery.datetimepicker.full.min.js')}}"></script>
@endsection

resources/views/notice/edit_delete.blade.php
@section('styles')
<link rel="stylesheet" href="{{ asset('css/jquery.datetimepicker.css') }}" type="text/css">
@endsection
@extends('layouts.master')
@section('content')
<h3 class="mt-4">｜　お知らせ登録</h3>
<br>
<div class="card">
    <form action="{{route('notice.update', $notice->ANNOUNCEMENTID)}}" method="POST" id="noticeFormEdit">
        @method('PATCH')
        @csrf
        <div class="card-body">
            <div class="form-group row">
                <div class="col-sm-2">
                    <div class="row">
                        <label for="staticEmail" class="col-sm-6 col-form-label">タイトル</label>
                        <div class="col-sm-6 text-center"><span class="badge badge-danger align-middle ">必須</span></div>
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-11">
                            <input type="text" name="title" class="form-control" value="{{$notice->TITLE}}">
                            @error('title')
                                <h6 class="text-danger">(*){{ $message }}</h6>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-2">
                    <div class="row">
                        <label for="staticEmail" class="col-sm-6 col-form-label">公開開始日時</label>
                        <div class="col-sm-6 text-center"><span class="badge badge-danger align-middle">必須</span></div>
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-11">
                            <input type="text" name="registrationDate" class="form-control registrationDate" value="{{$notice->REGISTRATIONDATE}}">
                            @error('registrationDate')
                                <h6 class="text-danger">(*){{ $message }}</h6>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-2">
                    <div class="row">
                        <label for="staticEmail" class="col-sm-6 col-form-label">公開終了日時</label>
                        <div class="col-sm-6 text-center"><span class="badge badge-danger align-middle">必須</span></div>
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-11">
                            <input type="text" name="expirationDateTime" class="form-control expirationDateTime" value="{{$notice->EXPIRATIONDATETIME}}">
                            @error('expirationDateTime')
                                <h6 class="text-danger">(*){{ $message }}</h6>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-2">
                    <div class="row">
                        <label for="staticEmail" class="col-sm-6 col-form-label">通知対象契約顧客</label>
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-11">
                            <div class="row">
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="tenantID" id="tenantID" value="{{$notice->TENANTID}}" readonly>
                                </div>
                                <div class="col-sm-2">
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-md btn-primary w-100" data-toggle="modal" data-target="#exampleModal">
                                        戻る
                                    </button>

                                    <!-- Modal -->
                                    <div class="modal fade mt-5" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <table class="table table-bordered text-center" id="tableTenant">
                                                        <thead class="thead-dark">
                                                            <tr>
                                                                <th scope="col">TENANTID</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr class="clickableRow">
                                                                <td>1</th>
                                                            </tr>
                                                            <tr class="clickableRow">
                                                                <td>2</th>
                                                            </tr>
                                                            <tr class="clickableRow">
                                                                <td>3</th>
                                                            </tr>
                                                            <tr class="clickableRow">
                                                                <td>4</th>
                                                            </tr>
                                                    </table>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="button" class="btn btn-primary" id="saveTenantId">Save changes</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- <div class="col-sm-1">
                            <button type="button" class="btn btn-success rounded-circle" aria-label="Close"><i class="fa fa-times"></i></button>
                        </div> -->
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-2">
                    <div class="row">
                        <label for="staticEmail" class="col-sm-6 col-form-label">本文</label>
                        <div class="col-sm-6 text-center"><span class="badge badge-danger align-middle">必須</span></div>
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-11">
                            <textarea class="form-control" rows="4" name="body">{{$notice->BODY}}</textarea>
                            @error('body')
                                <h6 class="text-danger">(*){{ $message }}</h6>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <div class="form-group row">
        <div class="col-sm-3"></div>
        <div class="col-sm-9">
            <div class="row text-center">
                <div class="col-sm-3">
                    <a href="{{route('notice.index')}}"><input type="button" class="btn btn-md btn-success w-50" value="戻る"></a>
                </div>
                <div class="col-sm-3">
                    <form action="{{route('notice.destroy', $notice->ANNOUNCEMENTID)}}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button class="btn btn-md btn-danger w-50">削除</button>
                    </form>
                </div>
                <div class="col-sm-3">
                    <button type="submit" class="btn btn-md btn-success w-50" id="noticeEditButton">変更</button>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript" src="{{asset('js/notice/edit_delete.js')}}"></script>
<script type="text/javascript" src="{{asset('js/jquery.datetimepicker.full.min.js')}}"></script>
<script type="text/javascript" src="{{asset('js/confirm_delete.js')}}"></script>
@endsection

resources/views/notice/list.blade.php
@extends('layouts.master')
@section('content')
<h3 class="mt-4">｜　お知らせ一覧</h3>
<br>
<div class="row">
    <div class="col-lg-8">
        @if(Session::has('msg'))
        <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('msg') }}</p>
        @endif
    </div>
    <div class="col-lg-4">
        <div class="form-group">
            <div class="row">
                <div class="col-sm-4"></div>
                <div class="col-sm-4"></div>
                <div class="col-sm-4">
                    <a href="{{route('notice.create')}}"><button class="btn btn-md btn-secondary w-100">新規登録</button></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <table class=" table table-bordered text-center">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">タイトル</th>
                    <th scope="col">公開開始日時</th>
                    <th scope="col">公開終了日時</th>
                    <th scope="col">対象</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach($listNotice as $item)
                <tr>
                    <th scope="row">{{$item->TITLE}}</th>
                    <td>{{$item->REGISTRATIONDATE}}</td>
                    <td>{{$item->EXPIRATIONDATETIME}}</td>
                    <td>全て</td>
                    <td><a href="{{route('notice.edit', $item->ANNOUNCEMENTID)}}"><input type="button" class="btn btn-success" value="編集"></a></td>
                </tr>
                @endforeach
        </table>
    </div>
    <div class="col-sm-12">
        <nav class="nav justify-content-center">
            {!! $listNotice->appends($_GET)->links() !!}
        </nav>
    </div>
</div>

@endsection