routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::view('/login', 'login/index');

// Route::group(['middleware' => 'guest'], function () {

// });
Route::get('/login', 'Auth\LoginController@login')->name('login')->middleware('guest');;
Route::post('/login', 'Auth\LoginController@doLogin');
// Route::get('logout', array('uses' => 'Auth\LoginController@doLogout'));
Route::get('/logout', 'Auth\LoginController@doLogout')->name('logout');


    Route::view('/', 'dashboard/index')->name('dashboard');
    Route::view('/dashboard', 'dashboard/index')->name('dashboard');

    Route::view('/password-recovery', 'password_recovery/index')->name('password_recovery');

    Route::get('contract', function () {
        return view('contract/contract_customer');
    })->name('contract');

    Route::get('representative', function () {
        return view('contract/contract_representative');
    })->name('representative');

    Route::get('/manage-contract', function () {
        return view('contract/manage_contract');
    })->name('manage-contract');

    Route::get('contract-infor', function () {
        return view('contract/contract_infor');
    })->name('contract-infor');

    Route::get('contract-connection', function () {
        return view('contract/contract_connection');
    })->name('contract-connection');

    Route::get('contract-search', function () {
        return view('contract/contract_search');
    })->name('search');

    Route::resource('/baseplacement', 'Master\BaseplacemstController');

    Route::resource('/user', 'Master\UserController');
    
    Route::resource('/notice', 'NoticeController');

    Route::view('support-notice', 'support_notice/index')->name('support-notice');

    Route::view('billing', 'billing/index')->name('billing');


Route::resource('/phone', 'PhoneController');

app/Models/Phone.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Phone extends Model
{
    protected $table = 'phones';

    protected $fillable = ['name', 'model'];

    public function user(){
        return $this->belongsTo('App\Models\User');
    }
}

app/Http/Controllers/PhoneController.php
<?php

namespace App\Http\Controllers;

use App\Models\Phone;
use Illuminate\Http\Request;

class PhoneController extends Controller
{
    public function index(){
        $phone = Phone::all();
        return view('phone.index', compact('phone'));
    }

    public function edit(){

    }

    public function create(){
        return view('phone.create');
    }

    public function show(){

    }

    public function update(){}

    public function store(Request $request){
        $phone = new Phone;

        $phone->name = $request->name;
        $phone->model = $request->model;
        $phone->save();
        if($phone){
            return redirect()->route('phone.index');
        }else{
            dd('error');
        }
    }
}

resources/views/phone/create.blade.php
@extends('layouts.master')
@section('content')
<h3 class="mt-4">Create phone</h3>
<br>
<div class="col-lg-8">
    @if(Session::has('msg'))
    <p  class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('msg') }}</p>
    @endif
</div>
<div class="card">
    <form action="{{route('phone.store')}}" method="POST"  >
        @csrf
        <div class="card-body">
            <div class="form-group row">
                <div class="col-sm-2">
                    <div class="row">
                        <label for="" class="col-sm-6 col-form-label">Name</label>
                        <div class="col-sm-6 text-center"><span class="badge badge-danger align-middle">必須</span></div>
                    </div>
                </div>
                
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-11">
                            <input type="text" class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}" name="name" >
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-2">
                    <div class="row">
                        <label for="" class="col-sm-6 col-form-label">Model</label>
                        <div class="col-sm-6 text-center"><span class="badge badge-danger align-middle">必須</span></div>
                    </div>
                </div>
                
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-11">
                            <input type="text" class="form-control @error('model') is-invalid @enderror" value="{{ old('model') }}" name="model" >
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-9">
                <div class="text-center" >
                    
                    <div class="row">
                        <div class="col-lg-6">
                            <a href="{{route('phone.index')}}"><input type="button" class="btn btn-md btn-success w-25"  value="戻る"></a>
                        </div>
                        <div class="col-lg-6">
                            <button class="btn btn-md btn-success w-25" id="show-loading">登録</button>
                        </div>
                    </div>
                    <br>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection
@section('scripts')
{{-- get element with id= show-loading --}}
<script type="text/javascript" src="{{asset('js/master/base/process.js')}}"></script>
@endsection

resources/views/phone/edit.blade.php
@extends('layouts.master')
@section('content')
<h3 class="mt-4">Edit phone</h3>
<br>
<div class="card">
    <form action="{{route('baseplacement.update', $baseplacement->id)}}" method="post" id="my_form"  >
        @method('PATCH')
        @csrf
        <div class="card-body">
            <div class="form-group row">
                <div class="col-sm-2">
                    <div class="row">
                        <label for="" class="col-sm-6 col-form-label">拠点名</label>
                        <div class="col-sm-6 text-center"><span class="badge badge-danger align-middle">必須</span></div>
                    </div>
                </div>
                
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-11">
                            <input name="baseplacement_name" type="text" class="form-control @error('baseplacement_name') is-invalid  @enderror " required value="{{$baseplacement->baseplacement_name}}">
                            @error('baseplacement_name')
                                <h6 class="text-danger">(*){{ $message }}</h6>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-9">
            <div class="text-center" >
                <div class="row">
                    <div class="col-lg-4">
                        <a href="{{route('baseplacement.index')}}"><input type="button" class="btn btn-md btn-success w-50"  value="戻る"></a>
                    </div>
                    <div class="col-lg-4">
                        <form action="{{route('baseplacement.destroy', $baseplacement->id)}}" method="post">
                            @method('DELETE')
                            @csrf
                            <button class="btn btn-md btn-danger w-50" >変更</button>
                        </form>
                    </div>
                    <div class="col-lg-4">
                        <button  name="submit" onclick="update()" id="show-loading" class="btn btn-md btn-success w-50" >削除</button>
                    </div>
                </div>
                <br>
            </div>
        </div>
    </div>
</div>

@endsection
@section('scripts')
{{-- get element with id= show-loading --}}
<script type="text/javascript" src="{{asset('js/master/base/process.js')}}"></script>
<script type="text/javascript" src="{{asset('js/master/base/delete.js')}}"></script>
<script type="text/javascript" src="{{asset('js/confirm_delete.js')}}"></script>
@endsection

resources/views/phone/index.blade.php
@extends('layouts.master')
@section('content')
<h3 class="mt-4">Phone</h3>
<br>
<div class="row">
    <div class="col-lg-8">
        @if(Session::has('msg'))
        <p  class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('msg') }}</p>
        @endif
    </div>
    <div class="col-lg-4">
        <form action="" class="form-group">
            <div class="row">
                <div class="col-lg-4"></div>
                <div class="col-lg-4"></div>
                <div class="col-lg-4"><a href="{{route('phone.create')}}"><input type="button" class="btn btn-md btn-secondary w-100"  value="新規登録"></a></div>
            </div>
        </form>
    </div>
</div>

<div class="card text-center">
    <div >
        <table class=" table table-bordered">
            <div>
                <div class="col-lg-8">
                    <thead class="thead-dark" >
                        <tr style="text-align: center; ">
                            <th scope="col" >Name</th>
                            <th scope="col" >Model</th>
                            <th scope="col"></th>
                            
                        </tr>
                    </thead>
                </div>
                <div class="col-lg-4">
                    <tbody >
                        @foreach ($phone as $p)
                        
                        <tr style="text-align: center; ">
                            <th scope="row">{{$p->name}}</th>
                            <th scope="row">{{$p->model}}</th>
                            <td><a href=""><input type="button" class="btn btn-success" value="編集"></a></td>
                        </tr>
                        @endforeach
                        
                    </tbody>
                </div>
                
            </div>
        </table>
    </div>
    <div class="card-footer">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-2"></div>
        </div>
    </div>
</div>



@endsection