routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::view('/login', 'login/index');

// Route::group(['middleware' => 'guest'], function () {

// });
Route::get('/login', 'Auth\LoginController@login')->name('login')->middleware('guest');;
Route::post('/login', 'Auth\LoginController@doLogin');
// Route::get('logout', array('uses' => 'Auth\LoginController@doLogout'));
Route::get('/logout', 'Auth\LoginController@doLogout')->name('logout');


    Route::view('/', 'dashboard/index')->name('dashboard');
    Route::view('/dashboard', 'dashboard/index')->name('dashboard');

    Route::view('/password-recovery', 'password_recovery/index')->name('password_recovery');

    Route::get('contract', function () {
        return view('contract/contract_customer');
    })->name('contract');

    Route::get('representative', function () {
        return view('contract/contract_representative');
    })->name('representative');

    Route::get('/manage-contract', function () {
        return view('contract/manage_contract');
    })->name('manage-contract');

    Route::get('contract-infor', function () {
        return view('contract/contract_infor');
    })->name('contract-infor');

    Route::get('contract-connection', function () {
        return view('contract/contract_connection');
    })->name('contract-connection');

    Route::get('contract-search', function () {
        return view('contract/contract_search');
    })->name('search');

    Route::resource('/baseplacement', 'Master\BaseplacemstController');

    Route::resource('/user', 'Master\UserController');
    
    Route::resource('/notice', 'NoticeController');

    Route::view('support-notice', 'support_notice/index')->name('support-notice');

    Route::view('billing', 'billing/index')->name('billing');


Route::resource('/phone', 'PhoneController');

resources/views/layouts/header.blade.php
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="index.html">Start Bootstrap</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        　<p style="color: aliceblue; margin-top: 20px">愛詩井太郎　さん</p>　
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">Settings</a>
                <a class="dropdown-item" href="#">Activity Log</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ route('logout') }}">Logout</a>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="{{ asset('css/styles.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('css/my-style.css') }}" rel="stylesheet" type="text/css"/>
    <!-- font-awesome/5.13.0 -->
    <script src="{{ asset('js/all.min.js') }}" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ asset('css/jquery-ui.css') }}" type="text/css">
    @yield('styles')
</head>

<body class="sb-nav-fixed">
    @include('layouts.header')
    <div id="layoutSidenav">
        @include('layouts.sidebar')
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @yield('content')
                </div>
            </main>
        </div>
    </div>
    <div id="overlay">
        <div class="cv-spinner">
            <span class="spinner"></span>
        </div>
    </div>
    <script src="{{ asset('js/jquery-3.5.1.min.js') }}" crossorigin="anonymous"></script>
    <script src="{{ asset('js/bootstrap.bundle.min.js') }}" crossorigin="anonymous"></script>
    <script src="{{ asset('js/scripts.js') }}"></script>
    <script src="{{ asset('js/jquery-ui.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/sweetalert.min.js') }}"></script>
    <script>
        $(function() {
            $("#datepicker").datepicker();
        });
    </script>
    @yield('scripts')
</body>

</html>

resources/views/layouts/sidebar.blade.php
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav" style="margin-left:20px">
                <a href="{{route('contract')}}" class="nav-link collapsed" >
                    契約顧客
                </a>
                <a class="nav-link collapsed" href="{{route('search')}}" >
                    イベント
                </a>
                <a class="nav-link collapsed" href="{{route('notice.index')}}" >
                    お知らせ
                </a>
                <a class="nav-link collapsed" href="{{route('support-notice')}}" >
                    支払通知
                </a>
                <a class="nav-link collapsed" href="{{route('billing')}}" >
                    精算・請求
                </a>
                <a class="nav-link collapsed" href="{{route('phone.index')}}">
                    Phone
                </a>
                <div class="dropdown show">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                        マスタ
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="{{route('baseplacement.index')}}">Base</a>
                            <a class="nav-link" href="{{route('user.index')}}">User</a>
                        </nav>
                    </div>
                </div>
                
            </div>
        </div>
    </nav>
</div>